// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/receipt.proto

package receipt

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Receipt service

func NewReceiptEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Receipt service

type ReceiptService interface {
	Call(ctx context.Context, in *Message, opts ...client.CallOption) (*Response, error)
	Scan(ctx context.Context, in *ScanRequest, opts ...client.CallOption) (*ScanResponse, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Receipt_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Receipt_PingPongService, error)
}

type receiptService struct {
	c    client.Client
	name string
}

func NewReceiptService(name string, c client.Client) ReceiptService {
	return &receiptService{
		c:    c,
		name: name,
	}
}

func (c *receiptService) Call(ctx context.Context, in *Message, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Receipt.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *receiptService) Scan(ctx context.Context, in *ScanRequest, opts ...client.CallOption) (*ScanResponse, error) {
	req := c.c.NewRequest(c.name, "Receipt.Scan", in)
	out := new(ScanResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *receiptService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Receipt_StreamService, error) {
	req := c.c.NewRequest(c.name, "Receipt.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &receiptServiceStream{stream}, nil
}

type Receipt_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type receiptServiceStream struct {
	stream client.Stream
}

func (x *receiptServiceStream) Close() error {
	return x.stream.Close()
}

func (x *receiptServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *receiptServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *receiptServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *receiptServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *receiptService) PingPong(ctx context.Context, opts ...client.CallOption) (Receipt_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Receipt.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &receiptServicePingPong{stream}, nil
}

type Receipt_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type receiptServicePingPong struct {
	stream client.Stream
}

func (x *receiptServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *receiptServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *receiptServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *receiptServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *receiptServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *receiptServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Receipt service

type ReceiptHandler interface {
	Call(context.Context, *Message, *Response) error
	Scan(context.Context, *ScanRequest, *ScanResponse) error
	Stream(context.Context, *StreamingRequest, Receipt_StreamStream) error
	PingPong(context.Context, Receipt_PingPongStream) error
}

func RegisterReceiptHandler(s server.Server, hdlr ReceiptHandler, opts ...server.HandlerOption) error {
	type receipt interface {
		Call(ctx context.Context, in *Message, out *Response) error
		Scan(ctx context.Context, in *ScanRequest, out *ScanResponse) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Receipt struct {
		receipt
	}
	h := &receiptHandler{hdlr}
	return s.Handle(s.NewHandler(&Receipt{h}, opts...))
}

type receiptHandler struct {
	ReceiptHandler
}

func (h *receiptHandler) Call(ctx context.Context, in *Message, out *Response) error {
	return h.ReceiptHandler.Call(ctx, in, out)
}

func (h *receiptHandler) Scan(ctx context.Context, in *ScanRequest, out *ScanResponse) error {
	return h.ReceiptHandler.Scan(ctx, in, out)
}

func (h *receiptHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.ReceiptHandler.Stream(ctx, m, &receiptStreamStream{stream})
}

type Receipt_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type receiptStreamStream struct {
	stream server.Stream
}

func (x *receiptStreamStream) Close() error {
	return x.stream.Close()
}

func (x *receiptStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *receiptStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *receiptStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *receiptStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *receiptHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.ReceiptHandler.PingPong(ctx, &receiptPingPongStream{stream})
}

type Receipt_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type receiptPingPongStream struct {
	stream server.Stream
}

func (x *receiptPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *receiptPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *receiptPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *receiptPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *receiptPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *receiptPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
