// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/org.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Org service

func NewOrgEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Org service

type OrgService interface {
	Lookup(ctx context.Context, in *LookupRequest, opts ...client.CallOption) (*LookupResponse, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Org_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Org_PingPongService, error)
}

type orgService struct {
	c    client.Client
	name string
}

func NewOrgService(name string, c client.Client) OrgService {
	return &orgService{
		c:    c,
		name: name,
	}
}

func (c *orgService) Lookup(ctx context.Context, in *LookupRequest, opts ...client.CallOption) (*LookupResponse, error) {
	req := c.c.NewRequest(c.name, "Org.Lookup", in)
	out := new(LookupResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Org_StreamService, error) {
	req := c.c.NewRequest(c.name, "Org.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &orgServiceStream{stream}, nil
}

type Org_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type orgServiceStream struct {
	stream client.Stream
}

func (x *orgServiceStream) Close() error {
	return x.stream.Close()
}

func (x *orgServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *orgServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *orgServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *orgServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *orgService) PingPong(ctx context.Context, opts ...client.CallOption) (Org_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Org.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &orgServicePingPong{stream}, nil
}

type Org_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type orgServicePingPong struct {
	stream client.Stream
}

func (x *orgServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *orgServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *orgServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *orgServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *orgServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *orgServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Org service

type OrgHandler interface {
	Lookup(context.Context, *LookupRequest, *LookupResponse) error
	Stream(context.Context, *StreamingRequest, Org_StreamStream) error
	PingPong(context.Context, Org_PingPongStream) error
}

func RegisterOrgHandler(s server.Server, hdlr OrgHandler, opts ...server.HandlerOption) error {
	type org interface {
		Lookup(ctx context.Context, in *LookupRequest, out *LookupResponse) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Org struct {
		org
	}
	h := &orgHandler{hdlr}
	return s.Handle(s.NewHandler(&Org{h}, opts...))
}

type orgHandler struct {
	OrgHandler
}

func (h *orgHandler) Lookup(ctx context.Context, in *LookupRequest, out *LookupResponse) error {
	return h.OrgHandler.Lookup(ctx, in, out)
}

func (h *orgHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.OrgHandler.Stream(ctx, m, &orgStreamStream{stream})
}

type Org_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type orgStreamStream struct {
	stream server.Stream
}

func (x *orgStreamStream) Close() error {
	return x.stream.Close()
}

func (x *orgStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *orgStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *orgStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *orgStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *orgHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.OrgHandler.PingPong(ctx, &orgPingPongStream{stream})
}

type Org_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type orgPingPongStream struct {
	stream server.Stream
}

func (x *orgPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *orgPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *orgPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *orgPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *orgPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *orgPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
